language: elixir
elixir: 1.8
otp_release: 21.2
before_install: |
  set -o errexit
  set -o errtrace
  # set -o nounset # TravisCI is unclean
  set -o pipefail
after_script:
- |
  git --no-pager diff
  [[ 0 -eq $(git --no-pager diff --name-only | wc -l) ]]
- set +e
notifications:
  email:
    on_success: never
